categories:
  0: '前言'
  1: '第一卷　启航'
  2: '第二卷　新世界'
  3: '第三卷　新社会'
  4: '第四卷　新澳洲'
  5: '第五卷　进入'
  6: '第六卷　纷争'
  7: '第七卷　大陆'

characters:
  y001: '萧子山'
  y002: '文德嗣'
  y003: '王洛宾'
  y004: '展无涯'
  y005: '马千瞩'
  y006: '李一挝'
  y007: '李元元'
  y008: '金克绶'
  y009: '吴南海'
  y010: '常凯申'
#  y011: '罗铎'
#  y012: '钟利时'
#  y013: '钱水廷'
#  y014: '邬德'
#  y015: '司凯德'
#  y016: '程栋'
#  y017: '何鸣'
#  y018: '马甲'
#  y019: '于鄂水'
#  y020: '戴谐'
#  y021: '刘牧州'
#  y022: '杜雯'
#  y023: '杨云'
#  y024: '梅晚'
#  y025: '李运兴'
#  y026: '丁丁'
#  y027: '方非'
#  y028: '张好古'
#  y029: '谭明'
#  y030: '时袅仁'
#  y031: '艾贝贝'
#  y032: '刘三'
#  y033: '赵艳梅'
#  y034: '胡青白'
#  y035: '方忆静'
#  y036: '姬信'
#  y037: '单道谦'
#  y038: '严茗'
#  y039: '孟贤'
#  y040: '冉耀'
#  y041: '周洞天'
#  y042: '赵慢熊'
#  y043: '江山'
#  y044: '季退思'
#  y045: '季无声'
#  y046: '莫笑安'
#  y047: '林深河'
#  y048: '黄大山'
#  y049: '杨宝贵'
#  y050: '叶雨茗'
#  y051: '吴旷明'
#  y052: '陆荣'
#  y053: '季安'
#  y054: '张信'
#  y055: '东门吹雨'
#  y056: '魏爱文'
#  y057: '洪璜楠'
#  y058: '索普'
#  y059: '付三思'
#  y060: '北炜'
#  y061: '应愈'
#  y062: '潘达'
#  y063: '白羽'
#  y064: '陈海阳'
#  y065: '李迪'
#  y066: '李海平'
#  y067: '林传清'
#  y068: '高晓松'
#  y069: '何影'
#  y070: '裔凡'
#  y071: '熊卜佑'
#  y072: '李亚阳'
#  y073: '宁静海'
#  y074: '席亚洲'
#  y075: '钱水协'
#  y076: '季润之'
#  y077: '卓天敏'
#  y078: '何方回'
#  y079: '河马'
#  y080: '刘翔'
#  y081: '费祀'
#  y082: '刘易晓'
#  y083: '孔令洋'
#  y084: '林佰光'
#  y085: '郑尚洁'
#  y086: '石志奇'
#  y087: '乐琳'
#  y088: '洛辰'
#  y089: '洪水尹'
#  y090: '文同'
#  y091: '严茂达'
#  y092: '谌天雄'
#  y093: '贝凯'
#  y094: '白国士'
#  y095: '冯宗泽'
#  y096: '南宫无敌'
#  y097: '尼克'
#  y098: '魏八尺'
#  y099: '洪劳军'
#  y100: '雷恩'
#  y101: '朱鸣夏'
#  y102: '鹿文渊'
#  y103: '陈思根'
#  y104: '冷凝云'
#  y105: '童贯'
#  y106: '赵引弓'
#  y107: '薛若望'
#  y108: '平秋盛'
#  y109: '慕泉'
#  y110: '田顺花'
#  y111: '赵晓芹'
#  y112: '乌云花'
#  y113: '莫水'
#  y114: '独墨'
#  y115: '陈策'
#  y116: '董薇薇'
#  y117: '阳河'
#  y118: '袁秋实'
#  y119: '唐糖'
#  y120: '常师德'
#  y121: '刘月菲'
#  y122: '午木'
#  y123: '乌佛'
#  y124: '周伯韬'
#  y125: '尤国团'
#  y126: '伊龙纹'
#  y127: '裴莉秀'
#  y128: '王鼎'
#  y129: '李炎'
#  y130: '许可'
#  y131: '徐天琦'
#  y132: '张彪'
#  y133: '吉谏章'
#  y134: '程逆风'
#  y135: '黄骅'
#  y136: '萧白朗'
#  y137: '萧贵'
#  y138: '周比利'
#  y139: '姜野'
#  y140: '孙立'
#  y141: '梁信'
#  y142: '李赤骑'
#  y143: '江牧之'
#  y144: '周克'
#  y145: '施建涛'
#  y146: '汤梦龙'
#  y147: '黄天宇'
#  y148: '蒋宏军'
#  y149: '林汉隆'
#  y150: '伍子衿'
#  y151: '凌天'
#  y152: '郧素济'
#  y153: '徐营捷'
#  y154: '史大富'
#  y155: '田九九'
#  y156: '李潇侣'
#  y157: '燕雀志'
#  y158: '冰风'
#  y159: '张兴培'
#  y160: '梅林'
#  y161: '甄倩'
#  y162: '张力平'
#  y163: '法石禄'
#  y164: '万里煌'
#  y165: '胡义成'
#  y166: '万里辉'
#  y167: '独孤求婚'
#  y168: '海林'
#  y169: '贾莫非'
#  y170: '叶孟言'
#  y171: '熊茂璋'
#  y172: '游老虎'
#  y173: '余志潜'
#  y174: '朱全兴'
#  y175: '吕泽扬'
#  y176: '李军'
#  y177: '王涛'
#  y178: '张柏林'
#  y179: '胡候'
#  y180: '蒙德'
#  y181: '李子平'
#  y182: '吕洋'
#  y183: '王瑞相'
#  y184: '老狄'
#  y185: '绍宗'
#  y186: '单良'
#  y187: '胡木野'
#  y188: '张雨'
#  y189: '张宇辰'
#  y190: '计启立'
#  y191: '石开'
#  y192: '张子怡'
#  y193: '何平'
#  y194: '兰阳阳'
#  y195: '周韦森'
#  y196: '查梧础'
#  y197: '江秋堰'
#  y198: '张土木'
#  y199: '张智翔'
#  y200: '白雨'
#  y201: '袁子光'
#  y202: '蒋佑中'
#  y203: '肖照川'
#  y204: '钱校长'
#  y205: '潘潘'
#  y206: '吕中行'
#  y207: '柳正'
#  y208: '崔云红'
#  y209: '黄爪子'
#  y210: '沈跃风'
#  y211: '赵雪'
#  y212: '张易坤'
#  y213: '吴石芒'
#  y214: '白多碌'
#  y215: '张应宸'
#  y216: '戴锷'
#  y217: '迪亚娜·门多萨'
#  y218: '方敬涵'
#  y219: '安熙'
#  y220: '董时叶'
#  y221: '金枝娇'
#  y222: '潘锋'
#  y223: '柳水心'
#  y224: '成默'
#  y225: '程琳琳'
#  y226: '程馨馨'
#  y227: '何邪'
#  y228: '卓云帆'
#  y229: '钱朵朵'
#  y230: '林深叶'
#  y231: '安熙'
#  yl01: '郭逸'
#  yl02: '明朗'
#  yl03: '慕敏'
#  yl04: '李梅'
#  yl05: '明秋'
#  yl06: '薛子良'
#  yl07: '萨琳娜'
#  yl08: '魏斯·兰度'
