#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli') {
    echo 'Warning: lingao should be invoked via the CLI version of PHP, not the ' . PHP_SAPI . ' SAPI' . PHP_EOL;
}

$_ENV['HOME'] = getenv('HOME');

/**
 * @param $file
 * @return bool|mixed
 */
function includeIfExists($file)
{
    return file_exists($file) ? include $file . '' : false; // fix inspect
}

if ((!$loader = includeIfExists(__DIR__ . '/vendor/autoload.php')) && (!$loader = includeIfExists(__DIR__ . '/../../autoload.php'))) {
    echo 'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -sS https://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL;
    exit(1);
}

use larryli\lingao\Config;
use Symfony\Component\Console\Application;

Config::init(__DIR__ . '/config.yaml');

$app = new Application('Lingao Tools', '0.0.1');
$app->add(new larryli\lingao\AddCommand());
$app->add(new larryli\lingao\UpdateCommand());
$app->run();
